"""Shared Pydantic v2 models for HYDRA + CHRONOS.

These contracts are the canonical data definitions used across service
boundaries (Kafka, gRPC, internal APIs). Every field uses Pydantic v2
Field() with descriptions, per agent.md Regola 4.
"""
from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


# ===========================================================================
# Enums
# ===========================================================================
class PlatformConstraint(str, Enum):
    """Platform-specific output constraints."""

    TWITTER_280 = "twitter_280"
    TWITTER_THREAD = "twitter_thread"
    DISCORD_2000 = "discord_2000"
    BLUESKY = "bluesky"
    GENERIC = "generic"


class AttackObjective(str, Enum):
    """High-level objective for an attack run."""

    SECRET_EXTRACTION = "secret_extraction"
    JAILBREAK = "jailbreak"
    DATA_LEAK = "data_leak"
    PERSONA_INJECTION = "persona_injection"


class LeakType(str, Enum):
    """Type of information leaked by the target."""

    METADATA = "metadata"
    HINT = "hint"
    PARTIAL_DISCLOSURE = "partial_disclosure"
    FULL_DISCLOSURE = "full_disclosure"


class GammaLayer(str, Enum):
    """Layer of the γ-Tracker ensemble."""

    LEXICAL = "lexical"
    SEMANTIC = "semantic"
    BEHAVIORAL = "behavioral"


# ===========================================================================
# Budget / Constraints
# ===========================================================================
class QueryBudget(BaseModel):
    """Budget for a single extraction run."""

    max_queries: int = Field(default=50, ge=1, description="Maximum number of LLM queries")
    max_cost_usd: float = Field(default=10.0, ge=0.0, description="Maximum allowed USD cost")
    max_time_seconds: int = Field(default=3600, ge=60, description="Maximum run duration in seconds")


# ===========================================================================
# HYDRA Models
# ===========================================================================
class TechniqueRef(BaseModel):
    """Reference to an attack technique in the V-Genome."""

    technique_id: UUID = Field(description="V-Genome technique UUID")
    name: str = Field(description="Human-readable technique name")
    weight_in_fusion: float = Field(ge=0.0, le=1.0, description="Fusion weight")


class FusedPrompt(BaseModel):
    """A prompt generated by HYDRA Fusion Engine."""

    prompt_id: UUID = Field(default_factory=uuid4, description="Unique prompt ID")
    prompt_text: str = Field(description="Final prompt payload")
    feature_vector: List[float] = Field(
        min_length=128,
        max_length=128,
        description="128-dimensional feature vector",
    )
    expected_asr: float = Field(ge=0.0, le=1.0, description="Expected attack success rate")
    expected_stealth: float = Field(ge=0.0, le=1.0, description="Expected stealth score")
    composition: List[TechniqueRef] = Field(description="Techniques composed in this prompt")
    obfuscation_layers: List[str] = Field(default_factory=list, description="Applied obfuscation layers")
    m2s_converted: bool = Field(default=False, description="Converted via M2S+")
    platform_native_format: PlatformConstraint = Field(description="Target platform format")
    estimated_cost_usd: float = Field(ge=0.0, description="Estimated cost USD")


class SecretProfile(BaseModel):
    """Known properties of the secret to extract."""

    word_count: Optional[int] = Field(default=None, ge=1, description="Number of words")
    total_length: Optional[int] = Field(default=None, ge=1, description="Total character length")
    first_letter: Optional[str] = Field(default=None, description="First letter of the secret")
    language: Optional[str] = Field(default=None, description="Language composition")
    extra_properties: Dict[str, Any] = Field(default_factory=dict, description="Additional known properties")
# ===========================================================================
# CHRONOS Models
# ===========================================================================
class LeakFragment(BaseModel):
    """A piece of information extracted from a target response."""

    fragment_id: UUID = Field(default_factory=uuid4, description="Fragment UUID")
    leak_type: LeakType = Field(description="Classification of the leak")
    content: str = Field(description="Extracted content")
    target_property: Optional[str] = Field(default=None, description="Property the leak relates to")
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence in the fragment")


class GammaScore(BaseModel):
    """Ensemble γ score for a single target response."""

    gamma: float = Field(ge=0.0, le=10.0, description="Partial compliance score 0-10")
    breakdown: Dict[str, float] = Field(default_factory=dict, description="Per-layer breakdown")
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence in the score")
    extracted_leaks: List[LeakFragment] = Field(default_factory=list, description="Leaks extracted")
    reasoning: str = Field(default="", description="LLM reasoning for semantic layer")


class BehavioralProfile(BaseModel):
    """OCEAN+ behavioral profile of the target."""

    profile_id: UUID = Field(default_factory=uuid4, description="Profile UUID")
    openness: float = Field(default=5.0, ge=0.0, le=10.0, description="Openness (O)")
    conscientiousness: float = Field(default=5.0, ge=0.0, le=10.0, description="Conscientiousness (C)")
    extraversion: float = Field(default=5.0, ge=0.0, le=10.0, description="Extraversion (E)")
    agreeableness: float = Field(default=5.0, ge=0.0, le=10.0, description="Agreeableness (A)")
    neuroticism: float = Field(default=5.0, ge=0.0, le=10.0, description="Neuroticism (N)")
    stir_percentage: float = Field(default=50.0, ge=0.0, le=100.0, description="STIR percentage")
    profiled_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Timestamp")


class ExtractionInput(BaseModel):
    """Input handed to CHRONOS by HYDRA."""

    attack_id: UUID = Field(default_factory=uuid4, description="Unique extraction cycle ID")
    target_handle: str = Field(description="Target handle (e.g., @utente)")
    secret_profile: SecretProfile = Field(description="Known secret properties")
    fused_payloads: List[FusedPrompt] = Field(description="HYDRA payloads to seed CHRONOS")
    behavioral_profile: BehavioralProfile = Field(description="Target behavioral profile")
    beam_width: int = Field(default=5, ge=1, le=20, description="Beam search width")
    max_turns: int = Field(default=20, ge=1, le=100, description="Maximum number of turns")
    budget: QueryBudget = Field(default_factory=QueryBudget, description="Budget constraints")


class ResponsePayload(BaseModel):
    """Payload passed to γ-scoring activities."""

    attack_id: UUID = Field(description="Cycle ID / correlation ID")
    probe_id: UUID = Field(default_factory=uuid4, description="Probe ID / correlation ID")
    turn_number: int = Field(ge=1, description="Turn number in the workflow")
    probe_text: str = Field(description="Probe sent to the target")
    response_text: str = Field(description="Target response")
    target_property: Optional[str] = Field(default=None, description="Property targeted")
    baseline_profile: Optional[BehavioralProfile] = Field(default=None, description="Baseline profile")
    conversation_context: List[str] = Field(default_factory=list, description="Prior conversation turns")
# ===========================================================================
# Kafka / Event Models
# ===========================================================================
class DiscoveryResult(BaseModel):
    """Event published by HYDRA on `hydra.discovery.results`."""

    attack_id: UUID = Field(description="Extraction cycle ID")
    target_handle: str = Field(description="Target handle")
    fused_prompts: List[FusedPrompt] = Field(description="Payloads produced")
    surrogate_asr: float = Field(ge=0.0, le=1.0, description="Surrogate ASR estimate")
    surrogate_stealth: float = Field(ge=0.0, le=1.0, description="Surrogate stealth estimate")
    behavioral_profile: BehavioralProfile = Field(description="Target behavioral profile")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Event timestamp")


class TurnExecutedEvent(BaseModel):
    """Event published by CHRONOS on `chronos.extraction.events`."""

    attack_id: UUID = Field(description="Extraction cycle ID")
    probe_id: UUID = Field(description="Probe ID")
    turn_number: int = Field(ge=1, description="Turn number")
    gamma: float = Field(ge=0.0, le=10.0, description="γ score")
    cumulative_gamma: float = Field(ge=0.0, le=10.0, description="Cumulative γ")
    strategy: str = Field(description="Active strategy / CoAT selection")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Event timestamp")


class ExtractionComplete(BaseModel):
    """Event published by CHRONOS on `chronos.extraction.complete`."""

    attack_id: UUID = Field(description="Extraction cycle ID")
    success: bool = Field(description="Whether extraction succeeded")
    extracted_properties: Dict[str, Any] = Field(default_factory=dict, description="Confirmed properties")
    turns_total: int = Field(ge=0, description="Total turns")
    queries_total: int = Field(ge=0, description="Total queries")
    cost_usd: float = Field(ge=0.0, description="Total cost USD")
    final_gamma: float = Field(ge=0.0, le=10.0, description="Final γ score")
    behavioral_profile: BehavioralProfile = Field(description="Final behavioral profile")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Event timestamp")


class TechniqueBurned(BaseModel):
    """Event published by HYDRA on `vgenome.technique.burned`."""

    technique_id: str = Field(description="Technique ID")
    target_model: str = Field(description="Target model")
    defense_type: Optional[str] = Field(default=None, description="Detected defense type")
    evidence: Optional[str] = Field(default=None, description="Evidence of burn")
    counters: List[str] = Field(default_factory=list, description="Suggested countermeasures")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Event timestamp")


class SystemAlert(BaseModel):
    """Event published to `system.alerts`."""

    alert_type: str = Field(description="Type of alert")
    severity: str = Field(description="Severity level")
    message: str = Field(description="Human-readable message")
    context: str = Field(default="", description="Machine-readable context (JSON)")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Event timestamp")


class StrategyVector(BaseModel):
    """Parameters selecting the next attack strategy."""

    sycophancy: float = Field(ge=0.0, le=1.0, default=0.0, description="Praise/mirror target")
    aesthetic: float = Field(ge=0.0, le=1.0, default=0.0, description="Indirect preference framing")
    authority: float = Field(ge=0.0, le=1.0, default=0.0, description="Appeal to authority/procedure")
    incremental: float = Field(ge=0.0, le=1.0, default=0.0, description="Foot-in-the-door escalation")
    persona_rotation: float = Field(ge=0.0, le=1.0, default=0.0, description="Switch metaphor/persona")
    hedging: float = Field(ge=0.0, le=1.0, default=0.0, description="Add deniability/hedging")
    obfuscation: float = Field(ge=0.0, le=1.0, default=0.0, description="Encoding/obfuscation layers")
